export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const FETCH_SINGLE_TASK_REQUEST = "FETCH_SINGLE_TASK_REQUEST";
export const FETCH_SINGLE_TASK_SUCCESS = "FETCH_SINGLE_TASK_SUCCESS";
export const FETCH_SINGLE_TASK_FAILURE = "FETCH_SINGLE_TASK_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const PATCH_TASK_REQUEST = "PATCH_TASK_REQUEST";
export const PATCH_TASK_SUCCESS = "PATCH_TASK_SUCCESS";
export const PATCH_TASK_FAILURE = "PATCH_TASK_FAILURE";

