import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { fetchTasks } from "../redux";
import { singleTask } from "../models";

export default function Home() {
  const tasksArray: singleTask[] | undefined = useSelector(
    (state) => state.tasks.tasks
  );
  const dispatch = useDispatch();
  React.useEffect(() => {}, [tasksArray]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => dispatch(fetchTasks())}>FETCH TASKS</button>
      {console.log(tasksArray)}
      {tasksArray &&
        tasksArray?.map((task, id) => {
          return (
            <div key={id}>
              <h1>{task.name}</h1>
              <p>{task.description}</p>
            </div>
          );
        })}
    </div>
  );
}
